export const FETCH_SERIES_REQUEST = "FETCH_SERIES_REQUEST";
export const FETCH_SERIES_SUCCESS = "FETCH_SERIES_SUCCESS";
export const FETCH_SERIES_FAILURE = "FETCH_SERIES_FAILURE";

export const FETCH_SEASON_REQUEST = "FETCH_SEASON_REQUEST";
export const FETCH_SEASON_SUCCESS = "FETCH_SEASON_SUCCESS";
export const FETCH_SEASON_FAILURE = "FETCH_SEASON_FAILURE";

export const FETCH_SERIES_INFO_REQUEST = "FETCH_SERIES_INFO_REQUEST";
export const FETCH_SERIES_INFO_SUCCESS = "FETCH_SERIES_INFO_SUCCESS";
export const FETCH_SERIES_INFO_FAILURE = "FETCH_SERIES_INFO_FAILURE";